export const ACTION_TYPES = {
  CHANGE_INPUT: "CHANGE_INPUT",
  ADD_STEP: "ADD_STEP",
  UPDATE_STEP: "UPDATE_STEP",
  MOVE_UP_STEP: "MOVE_UP_STEP",
  MOVE_DOWN_STEP: "MOVE_DOWN_STEP",
  DELETE_STEP: "DELETE_STEP",
  ADD_URL: "ADD_URL",
  UPDATE_URL: "UPDATE_URL",
  DELETE_URL: "DELETE_URL",
  DELETE_IMAGE: "DELETE_IMAGE",
  ADD_INGREDIENTS: "ADD_INGREDIENTS",
  MOVE_UP_INGREDIENTS: "MOVE_UP_INGREDIENTS",
  MOVE_DOWN_INGREDIENTS: "MOVE_DOWN_INGREDIENTS",
  DELETE_INGREDIENTS: "DELETE_INGREDIENTS",
  ADD_TAG: "ADD_TAG",
  REMOVE_TAG: "ADD_TAG",


};